export const Constant = {
    BCRYPT_SALT: 5,
    ALLOWED_MOBILE_LENGTH: 10,
    ALLOWED_PASSWORD_MIN_LENGTH: 8,
    ALLOWED_PASSWORD_MAX_LENGTH: 16,
    ALLOWED_NAME_MIN_LENGTH: 3,
    ALLOWED_NAME_MAX_LENGTH: 50,
    JWT_SECRET: "aufdsv7623tx7t3bgci"
}